/**
 * Generated by openapi-to. DO NOT EDIT.
 * Regenerate from the OpenAPI document and openapi-to configuration.
 * @generated
 */

import type { AddressModel } from "./address.model.ts";
import type { RoleModel } from "./role.model.ts";
import type { UserOptionalInlineModeEnumValue } from "../enum.model.ts";
export interface UserModel {
  id: string;
  name: string;
  role: RoleModel;
  address?: AddressModel;
  optionalInline?: {
    count: number;
    mode?: UserOptionalInlineModeEnumValue;
  };
  tags?: Array<string>;
  metadata?: {
    [key: string]: string;
  };
}
