/**
 * Generated by openapi-to. DO NOT EDIT.
 * Regenerate from the OpenAPI document and openapi-to configuration.
 * @generated
 */

import type { GetSchemaLessResponse } from "./get-schema-less.types.ts";
import { http, HttpResponse } from "msw";

/** Whether to enable handler */
export const enabled = false;

/** */
export default function getSchemaLessHandler(data?: GetSchemaLessResponse) {
  return http.get(
    '/schema-less',
    (info) => {
      return HttpResponse.json(data, {
        status: 200,
      });
    },
  );
}
