/**
 * Generated by openapi-to. DO NOT EDIT.
 * Regenerate from the OpenAPI document and openapi-to configuration.
 * @generated
 */

export type GetUserPathParams = {
  userId: string;
};
export type GetUserHeaderParams = {
  "X-Tenant": string;
};
export type GetUserCookieParams = {
  session?: string;
};
export type GetUserResponse204 = undefined;
export type GetUserResponseError = unknown;
export type GetUserResponse = GetUserResponse204;
