/**
 * Generated by openapi-to. DO NOT EDIT.
 * Regenerate from the OpenAPI document and openapi-to configuration.
 * @generated
 */

import type { ErrorModel } from "../types/models/error.model.ts";
import type { UserModel } from "../types/models/user.model.ts";
export type GetUserPathParams = {
  userId: string;
};
export type GetUserQueryParams = {
  verbose?: boolean;
};
export type GetUserHeaderParams = {
  "X-Tenant": string;
};
export type GetUserCookieParams = {
  session?: string;
};
/**
 * @description Found
 */
export type GetUserResponse200 = UserModel;
/**
 * @description Missing
 */
export type GetUserResponse404 = ErrorModel;
/**
 * @description Unknown error
 */
export type GetUserResponseDefault = unknown;
export type GetUserResponseError = GetUserResponse404 | GetUserResponseDefault;
export type GetUserResponse = GetUserResponse200;
