/**
 * Generated by openapi-to. DO NOT EDIT.
 * Regenerate from the OpenAPI document and openapi-to configuration.
 * @generated
 */

import useSWR from "swr";
import type { GetHealthResponse, GetHealthResponseError } from "./get-health.types.ts";
import { getHealthService } from "./get-health.service.ts";
export const getHealthQueryKey = () => [{ url: '/health', method: 'get' }] as const;
export type GetHealthQueryKey = ReturnType<typeof getHealthQueryKey>;

/** */
export function useGetHealthQuery(options?: {
  query?: Parameters<typeof useSWR<GetHealthResponse, GetHealthQueryKey | null, any>>[2];
  shouldFetch?: boolean;
}) {

  const { query: queryOptions, shouldFetch = true } = options ?? {};
  const queryKey = getHealthQueryKey();

  return useSWR<
    GetHealthResponse,
    GetHealthResponseError,
    GetHealthQueryKey | null
  >(shouldFetch ? queryKey : null, {
    ...queryOptions,
    fetcher: async (_url) => {
      return getHealthService();
    }
  });
}
