/**
 * Generated by openapi-to. DO NOT EDIT.
 * Regenerate from the OpenAPI document and openapi-to configuration.
 * @generated
 */

export type KeepOperationResponse200 = undefined;
export type KeepOperationResponseError = unknown;
export type KeepOperationResponse = KeepOperationResponse200;
