import { lstat, readFile, realpath } from "node:fs/promises";
import path from "node:path";

export const WORKSPACE_HEADER = "# Generated by scripts/install-openapi-to-main.mjs";
export const CONSUMER_BUILD_ALLOWLIST = ["esbuild", "msw", "vue-demi"];
const SHA_PATTERN = /^[a-f0-9]{40,64}$/i;

function parseVersion(value) {
  const match = String(value).replace(/^v/, "").match(/^(\d+)(?:\.(\d+))?(?:\.(\d+))?(?:-([0-9A-Za-z.-]+))?(?:\+[0-9A-Za-z.-]+)?$/);
  if (!match) return undefined;
  return {
    major: Number(match[1]),
    minor: Number(match[2] ?? 0),
    patch: Number(match[3] ?? 0),
    prerelease: match[4],
  };
}

function compareVersions(left, right) {
  for (const key of ["major", "minor", "patch"]) {
    if (left[key] !== right[key]) return left[key] < right[key] ? -1 : 1;
  }
  if (left.prerelease === right.prerelease) return 0;
  if (left.prerelease === undefined) return 1;
  if (right.prerelease === undefined) return -1;
  const leftIdentifiers = left.prerelease.split(".");
  const rightIdentifiers = right.prerelease.split(".");
  for (let index = 0; index < Math.max(leftIdentifiers.length, rightIdentifiers.length); index += 1) {
    const leftIdentifier = leftIdentifiers[index];
    const rightIdentifier = rightIdentifiers[index];
    if (leftIdentifier === undefined) return -1;
    if (rightIdentifier === undefined) return 1;
    if (leftIdentifier === rightIdentifier) continue;
    const leftNumeric = /^\d+$/.test(leftIdentifier);
    const rightNumeric = /^\d+$/.test(rightIdentifier);
    if (leftNumeric && rightNumeric) {
      const leftNumber = BigInt(leftIdentifier);
      const rightNumber = BigInt(rightIdentifier);
      if (leftNumber !== rightNumber) return leftNumber < rightNumber ? -1 : 1;
      continue;
    }
    if (leftNumeric !== rightNumeric) return leftNumeric ? -1 : 1;
    return leftIdentifier < rightIdentifier ? -1 : 1;
  }
  return 0;
}

function satisfiesComparator(version, token) {
  const partialComparator = token.match(/^(>=|<=|>|<)(\d+)(?:\.(\d+))?$/);
  if (partialComparator && [">", "<="].includes(partialComparator[1])) {
    const operator = partialComparator[1];
    const major = Number(partialComparator[2]);
    const minor = partialComparator[3] === undefined ? undefined : Number(partialComparator[3]);
    const threshold = minor === undefined
      ? { major: major + 1, minor: 0, patch: 0, prerelease: operator === "<=" ? "0" : undefined }
      : { major, minor: minor + 1, patch: 0, prerelease: operator === "<=" ? "0" : undefined };
    return operator === ">"
      ? compareVersions(version, threshold) >= 0
      : compareVersions(version, threshold) < 0;
  }
  const tildeMajor = token.match(/^~(\d+)$/);
  if (tildeMajor) return version.major === Number(tildeMajor[1]) && compareVersions(version, { major: Number(tildeMajor[1]), minor: 0, patch: 0 }) >= 0;
  const partial = token.match(/^(?:=)?(\d+)(?:\.(\d+|[xX*]))?(?:\.(\d+|[xX*]))?$/);
  if (partial && (partial[2] === undefined || partial[3] === undefined || /[xX*]/.test(token))) {
    if (version.major !== Number(partial[1])) return false;
    if (partial[2] !== undefined && !/[xX*]/.test(partial[2]) && version.minor !== Number(partial[2])) return false;
    if (partial[3] !== undefined && !/[xX*]/.test(partial[3]) && version.patch !== Number(partial[3])) return false;
    return version.prerelease === undefined;
  }
  const match = token.match(/^(>=|<=|>|<|\^|~)?(.+)$/);
  const wanted = match && parseVersion(match[2]);
  if (!match || !wanted) return false;
  const operator = match[1] ?? "=";
  const compared = compareVersions(version, wanted);
  if (operator === ">=") return compared >= 0;
  if (operator === ">") return compared > 0;
  if (operator === "<=") return compared <= 0;
  if (operator === "<") return compared < 0;
  if (operator === "~") {
    return compared >= 0 && version.major === wanted.major && version.minor === wanted.minor;
  }
  if (operator === "^") {
    if (compared < 0) return false;
    if (wanted.major > 0) return version.major === wanted.major;
    if (wanted.minor > 0) return version.major === 0 && version.minor === wanted.minor;
    return version.major === 0 && version.minor === 0 && version.patch === wanted.patch;
  }
  return compared === 0;
}

function prereleaseComparatorTarget(token) {
  const partialComparator = token.match(/^(<=)(\d+)(?:\.(\d+))?$/);
  if (partialComparator) {
    const major = Number(partialComparator[2]);
    const minor = partialComparator[3] === undefined ? undefined : Number(partialComparator[3]);
    return minor === undefined
      ? { major: major + 1, minor: 0, patch: 0, prerelease: "0" }
      : { major, minor: minor + 1, patch: 0, prerelease: "0" };
  }
  const match = token.match(/^(>=|<=|>|<|\^|~)?(.+)$/);
  const target = match && parseVersion(match[2]);
  return target?.prerelease === undefined ? undefined : target;
}

export function satisfiesEngineRange(versionText, rangeText) {
  const version = parseVersion(versionText);
  if (!version || typeof rangeText !== "string" || rangeText.trim() === "") return false;
  return rangeText.split("||").some((alternative) => {
    const tokens = alternative.trim().split(/\s+/).filter(Boolean);
    if (tokens.length === 0) return false;
    if (
      version.prerelease !== undefined
      && !tokens.some((token) => {
        const target = prereleaseComparatorTarget(token);
        return target?.major === version.major && target.minor === version.minor && target.patch === version.patch;
      })
    ) return false;
    return tokens.every((token) => token === "*" || satisfiesComparator(version, token));
  });
}

export function inspectSourceToolchain(packageJson, nodeVersion) {
  const declaration = packageJson?.packageManager;
  const match = typeof declaration === "string"
    ? declaration.match(/^pnpm@(\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?)$/)
    : undefined;
  if (!match) {
    throw new Error(`Unsupported package manager declaration: ${JSON.stringify(declaration)}. Expected an exact pnpm@<version>.`);
  }

  const pnpmVersion = match[1];
  const engines = packageJson.engines ?? {};
  if (engines.node && !satisfiesEngineRange(nodeVersion, engines.node)) {
    throw new Error(`Unsupported Node ${nodeVersion}: source requires node ${engines.node}.`);
  }
  if (engines.pnpm && !satisfiesEngineRange(pnpmVersion, engines.pnpm)) {
    throw new Error(`Unsupported pnpm ${pnpmVersion}: source requires pnpm ${engines.pnpm}.`);
  }

  return { packageManager: declaration, pnpmVersion, engines };
}

export function createSourceIsolationProfile(
  homeDirectory,
  protectedFiles = [],
  homeAliases = [],
  protectedDirectories = [],
  protectedWriteSubpaths = [],
  protectedReadWriteSubpaths = [],
) {
  const homeDirectories = [homeDirectory, ...homeAliases];
  if (homeDirectories.some((directory) => typeof directory !== "string" || !path.isAbsolute(directory))) {
    throw new Error("Source isolation requires an absolute host home directory.");
  }
  if (!Array.isArray(protectedFiles) || protectedFiles.some((filename) => typeof filename !== "string" || !path.isAbsolute(filename))) {
    throw new Error("Source isolation protected files must be absolute paths.");
  }
  if (!Array.isArray(protectedDirectories) || protectedDirectories.some((directory) => typeof directory !== "string" || !path.isAbsolute(directory))) {
    throw new Error("Source isolation protected directories must be absolute paths.");
  }
  if (!Array.isArray(protectedWriteSubpaths) || protectedWriteSubpaths.some((subpath) => typeof subpath !== "string" || !path.isAbsolute(subpath))) {
    throw new Error("Source isolation protected write subpaths must be absolute paths.");
  }
  if (!Array.isArray(protectedReadWriteSubpaths) || protectedReadWriteSubpaths.some((subpath) => typeof subpath !== "string" || !path.isAbsolute(subpath))) {
    throw new Error("Source isolation protected read/write subpaths must be absolute paths.");
  }
  const escapePath = (value) => path.resolve(value).replaceAll("\\", "\\\\").replaceAll('"', '\\"');
  const escapedHomes = [...new Set(homeDirectories.map(escapePath))];
  return [
    "(version 1)",
    "(allow default)",
    ...escapedHomes.flatMap((home) => [
      `(deny file-read* (subpath "${home}"))`,
      `(deny file-write* (subpath "${home}"))`,
    ]),
    ...[...new Set(protectedReadWriteSubpaths.map(escapePath))].flatMap((subpath) => [
      `(deny file-read* (subpath "${subpath}"))`,
      `(deny file-write* (subpath "${subpath}"))`,
    ]),
    ...[...new Set(protectedDirectories.map(escapePath))].map((directory) => `(deny file-write* (literal "${directory}"))`),
    ...[...new Set(protectedWriteSubpaths.map(escapePath))].map((subpath) => `(deny file-write* (subpath "${subpath}"))`),
    ...protectedFiles.map((filename) => `(deny file-write* (literal "${escapePath(filename)}"))`),
    "",
  ].join("\n");
}

export function readInstalledPackageManager(modulesState) {
  if (typeof modulesState !== "string") return undefined;
  try {
    const parsed = JSON.parse(modulesState);
    if (typeof parsed.packageManager === "string") return parsed.packageManager;
  } catch {
    // Older pnpm versions wrote YAML rather than JSON to .modules.yaml.
  }
  const match = modulesState.match(/^\s*packageManager\s*:\s*["']?(pnpm@[^\s"']+)["']?\s*$/m);
  return match?.[1];
}

export function workspaceSourceHead(contents) {
  if (typeof contents !== "string") return undefined;
  const lines = contents.split(/\r?\n/);
  if (lines[0] !== WORKSPACE_HEADER) return undefined;
  const match = lines[1]?.match(/^# Source HEAD: ([a-f0-9]{40,64})$/i);
  return match?.[1];
}

export function isGeneratedWorkspaceYaml(contents) {
  return workspaceSourceHead(contents) !== undefined;
}

function parseGeneratedScalar(value) {
  if (value.startsWith('"')) return JSON.parse(value);
  if (value.startsWith("'")) return value.slice(1, -1).replaceAll("''", "'");
  return value;
}

export function validateGeneratedWorkspaceYaml(contents, packages) {
  const sourceHead = workspaceSourceHead(contents);
  if (!sourceHead || !Array.isArray(packages) || packages.length === 0) {
    throw new Error("workspace header or previous provenance package list is missing");
  }
  const sections = new Map();
  let currentSection;
  for (const line of contents.split(/\r?\n/).slice(2)) {
    if (!line.trim() || line.trimStart().startsWith("#")) continue;
    const section = line.match(/^([A-Za-z][A-Za-z0-9_-]*):\s*$/);
    if (section) {
      currentSection = section[1];
      if (sections.has(currentSection)) throw new Error(`duplicate workspace setting: ${currentSection}`);
      sections.set(currentSection, []);
      continue;
    }
    if (!currentSection) throw new Error("workspace contains content outside generated settings");
    sections.get(currentSection).push(line);
  }
  const expectedSections = ["overrides", "onlyBuiltDependencies", "allowBuilds"].sort();
  if ([...sections.keys()].sort().join("\0") !== expectedSections.join("\0")) {
    throw new Error("workspace contains unknown or missing top-level settings");
  }

  const expectedOverrides = new Map(packages.map(({ name, tarball }) => [
    name,
    `file:.openapi-to-local/${sourceHead}/tarballs/${tarball}`,
  ]));
  const actualOverrides = new Map();
  for (const line of sections.get("overrides")) {
    const entry = line.match(/^  (.+?):\s+(.+)$/);
    if (!entry) throw new Error("workspace overrides contain an unexpected entry");
    const name = parseGeneratedScalar(entry[1]);
    const value = parseGeneratedScalar(entry[2]);
    if (actualOverrides.has(name)) throw new Error(`duplicate workspace override: ${name}`);
    actualOverrides.set(name, value);
  }
  if (
    actualOverrides.size !== expectedOverrides.size
    || [...expectedOverrides].some(([name, value]) => actualOverrides.get(name) !== value)
  ) {
    throw new Error("workspace overrides do not match the prior provenance package list");
  }

  const actualBuildAllowlist = sections.get("onlyBuiltDependencies")
    .map((line) => line.match(/^  - ([A-Za-z0-9@._/-]+)$/)?.[1]);
  if (actualBuildAllowlist.includes(undefined) || actualBuildAllowlist.join("\0") !== CONSUMER_BUILD_ALLOWLIST.join("\0")) {
    throw new Error("workspace build dependency allowlist does not match this script");
  }

  const actualBuildApprovals = new Map();
  for (const line of sections.get("allowBuilds")) {
    const entry = line.match(/^  ([A-Za-z0-9@._/-]+): (true|false)$/);
    if (!entry) throw new Error("workspace build approvals contain an unexpected entry");
    actualBuildApprovals.set(entry[1], entry[2]);
  }
  if (
    actualBuildApprovals.size !== CONSUMER_BUILD_ALLOWLIST.length
    || CONSUMER_BUILD_ALLOWLIST.some((name) => actualBuildApprovals.get(name) !== "true")
  ) {
    throw new Error("workspace build approvals do not match the reviewed script set");
  }
}

export function createProvenance({ sourceHead, packageManager, nodeVersion, packedAt, packages }) {
  if (!SHA_PATTERN.test(sourceHead)) throw new Error(`Invalid provenance source HEAD: ${sourceHead}`);
  if (typeof packageManager !== "string" || !packageManager.startsWith("pnpm@")) {
    throw new Error("Provenance must record the exact pnpm packageManager declaration.");
  }
  if (typeof nodeVersion !== "string" || !nodeVersion) throw new Error("Provenance must record the Node version.");
  if (!Array.isArray(packages) || packages.length === 0) throw new Error("Provenance must contain packed packages.");
  for (const item of packages) {
    if (
      !item
      || typeof item.name !== "string"
      || typeof item.version !== "string"
      || typeof item.tarball !== "string"
      || typeof item.path !== "string"
      || !Number.isSafeInteger(item.bytes)
      || !/^[a-f0-9]{64}$/i.test(item.sha256)
      || item.sourceHead !== sourceHead
    ) {
      throw new Error("A provenance package entry is missing required artifact identity fields.");
    }
  }
  return {
    schemaVersion: 1,
    source: { repository: "openapi-to/openapi-to", ref: "main", head: sourceHead },
    packageManager,
    node: nodeVersion,
    packedAt,
    packages,
  };
}

export function validatePriorArtifactProvenance(provenance, sourceHead) {
  if (
    !provenance
    || provenance.schemaVersion !== 1
    || provenance.source?.repository !== "openapi-to/openapi-to"
    || provenance.source?.ref !== "main"
    || provenance.source?.head !== sourceHead
    || !Array.isArray(provenance.packages)
    || provenance.packages.length === 0
  ) throw new Error("provenance source identity or package list is invalid");

  const names = new Set();
  const filenames = new Set();
  for (const item of provenance.packages) {
    const expectedPath = `.openapi-to-local/${sourceHead}/tarballs/${item?.tarball}`;
    if (
      !item
      || typeof item.name !== "string"
      || !item.name
      || names.has(item.name)
      || typeof item.version !== "string"
      || !item.version
      || !isSafeTarballFilename(item.tarball)
      || filenames.has(item.tarball)
      || item.path !== expectedPath
      || !Number.isSafeInteger(item.bytes)
      || item.bytes <= 0
      || !/^[a-f0-9]{64}$/i.test(item.sha256)
      || !/^sha512-[A-Za-z0-9+/]{86}==$/.test(item.integrity)
      || item.sourceHead !== sourceHead
    ) throw new Error("provenance contains an invalid or duplicate package artifact entry");
    names.add(item.name);
    filenames.add(item.tarball);
  }
  return provenance;
}

export function priorArtifactOwnsContent(provenance, filename, sha256, sourceHead) {
  try {
    validatePriorArtifactProvenance(provenance, sourceHead);
    return provenance.packages.some((item) => item.tarball === filename && item.sha256.toLowerCase() === sha256.toLowerCase());
  } catch {
    return false;
  }
}

export function createCurrentMainWorkspaceYaml({
  packed,
  sourceHead,
  createPackedOverrides,
  createWorkspaceOverridesYaml,
}) {
  if (!SHA_PATTERN.test(sourceHead)) throw new Error(`Invalid source HEAD: ${sourceHead}`);
  if (!Array.isArray(packed) || packed.length === 0) throw new Error("Canonical pack helper returned no packages.");
  const names = packed.map(({ name }) => name);
  if (new Set(names).size !== names.length || names.some((name) => typeof name !== "string" || !name)) {
    throw new Error("Canonical pack helper returned duplicate or invalid package names.");
  }

  const relativeArchives = new Map();
  const relativePacked = packed.map((item) => {
    if (
      !isSafeTarballFilename(item.filename)
    ) {
      throw new Error(`Invalid packed filename for ${item.name}: ${item.filename}`);
    }
    const archive = path.posix.join(".openapi-to-local", sourceHead, "tarballs", item.filename);
    relativeArchives.set(item.name, archive);
    return { ...item, archive };
  });
  const overrides = createPackedOverrides(relativePacked);
  if (Object.keys(overrides).length !== packed.length) {
    throw new Error("Canonical override helper did not return one override per packed package.");
  }
  for (const [name, archive] of relativeArchives) {
    if (overrides[name] !== `file:${archive}`) {
      throw new Error(`Canonical override helper returned a non-relative artifact path for ${name}.`);
    }
  }
  const yaml = createWorkspaceOverridesYaml(overrides);
  if (typeof yaml !== "string" || !yaml.startsWith("overrides:\n")) {
    throw new Error("Canonical workspace override helper returned unexpected YAML.");
  }
  const expectedPaths = Object.fromEntries(relativeArchives);
  const buildAllowlist = [
    "onlyBuiltDependencies:",
    ...CONSUMER_BUILD_ALLOWLIST.map((name) => `  - ${name}`),
    "",
  ].join("\n");
  const buildApprovals = [
    "allowBuilds:",
    ...CONSUMER_BUILD_ALLOWLIST.map((name) => `  ${name}: true`),
    "",
  ].join("\n");
  const result = {
    yaml: `${WORKSPACE_HEADER}\n# Source HEAD: ${sourceHead}\n# Consumer-only current-main test settings and narrow dependency build approvals.\n${yaml}\n${buildAllowlist}${buildApprovals}`,
    expectedPaths,
  };
  validateGeneratedWorkspaceYaml(result.yaml, packed.map(({ name, filename }) => ({ name, tarball: filename })));
  return result;
}

export function isSafeTarballFilename(filename) {
  return typeof filename === "string"
    && /^[@A-Za-z0-9][A-Za-z0-9@._-]*\.tgz$/.test(filename)
    && path.posix.basename(filename) === filename
    && path.win32.basename(filename) === filename;
}

function packageSections(lockText) {
  const lines = lockText.split(/\r?\n/);
  const packageIndex = lines.indexOf("packages:");
  if (packageIndex < 0) return [];
  const endIndex = lines.findIndex((line, index) => index > packageIndex && /^(?:snapshots|importers):$/.test(line));
  const stop = endIndex < 0 ? lines.length : endIndex;
  const sections = [];
  for (let index = packageIndex + 1; index < stop; index += 1) {
    if (!/^  (?:'[^']+'|"[^"]+"|[^ ].*):\s*$/.test(lines[index])) continue;
    const start = index;
    index += 1;
    while (index < stop && !/^  (?:'[^']+'|"[^"]+"|[^ ].*):\s*$/.test(lines[index])) index += 1;
    sections.push({ heading: lines[start], text: lines.slice(start, index).join("\n") });
    index -= 1;
  }
  return sections;
}

export function verifyLockfileLocalArtifacts(lockText, expectedPaths, expectedIntegrities = {}) {
  const sections = packageSections(lockText);
  const failures = [];
  for (const [name, relativePath] of Object.entries(expectedPaths)) {
    const fileSpec = `file:${relativePath}`;
    const packageEntries = sections.filter(({ heading }) => heading.includes(`${name}@`));
    if (packageEntries.length === 0) {
      failures.push(`${name}: no package resolution entry in pnpm-lock.yaml`);
      continue;
    }
    const fallback = packageEntries.filter(({ text }) => !text.includes(fileSpec));
    if (fallback.length > 0) failures.push(`${name}: lockfile contains a package resolution without ${fileSpec}`);
    const expectedIntegrity = expectedIntegrities[name];
    if (expectedIntegrity) {
      for (const { text } of packageEntries.filter(({ text: section }) => section.includes(fileSpec))) {
        const actualIntegrity = text.match(/\bintegrity:\s*(sha(?:256|384|512)-[A-Za-z0-9+/]+={0,2})/)?.[1];
        if (actualIntegrity !== expectedIntegrity) {
          failures.push(`${name}: lockfile integrity does not match the current local tarball.`);
          break;
        }
      }
    }
  }
  if (failures.length > 0) throw new Error(failures.join("\n"));
  return Object.keys(expectedPaths).length;
}

export async function verifyInstalledPackageVersions({ root, packed, sourceHead }) {
  const failures = [];
  const aggregate = packed.find(({ name }) => name === "openapi-to");
  if (!aggregate) failures.push("Canonical pack set is missing the openapi-to aggregate package.");
  let aggregatePath;
  let aggregateManifest;
  if (aggregate) {
    try {
      const rootPackagePath = path.join(root, "node_modules", "openapi-to");
      const rootPackageStat = await lstat(rootPackagePath);
      if (!rootPackageStat.isSymbolicLink()) {
        failures.push("openapi-to aggregate root installation is not a pnpm dependency symlink.");
      }
      aggregateManifest = JSON.parse(await readFile(path.join(rootPackagePath, "package.json"), "utf8"));
      if (aggregateManifest.version !== aggregate.version) {
        failures.push(`openapi-to aggregate installed ${aggregateManifest.version}, expected ${aggregate.version}.`);
      }
      aggregatePath = await realpath(rootPackagePath);
      if (!aggregatePath.includes(`${path.sep}.pnpm${path.sep}`)) {
        failures.push("openapi-to aggregate is not resolved from the pnpm virtual store.");
      }
      const sourceMarker = `file+.openapi-to-local+${sourceHead.slice(0, 20)}`.toLowerCase();
      if (!aggregatePath.toLowerCase().includes(sourceMarker)) {
        failures.push("openapi-to aggregate virtual-store path does not identify this source SHA's local tarball.");
      }
    } catch (error) {
      failures.push(`openapi-to aggregate is not installed: ${error.message}`);
    }
  }

  if (aggregatePath && aggregateManifest) {
    for (const item of packed) {
      const packagePath = item.name === "openapi-to"
        ? path.join(root, "node_modules", "openapi-to")
        : path.join(path.dirname(aggregatePath), ...item.name.split("/"));
      try {
        const manifest = JSON.parse(await readFile(path.join(packagePath, "package.json"), "utf8"));
        if (manifest.name !== item.name || manifest.version !== item.version) {
          failures.push(`${item.name}: installed ${manifest.name}@${manifest.version}, expected ${item.name}@${item.version}.`);
          continue;
        }
        if (item.name !== "openapi-to" && !(await lstat(packagePath)).isSymbolicLink()) {
          failures.push(`${item.name}: aggregate dependency is not linked through its pnpm node_modules tree.`);
        }
        const resolved = await realpath(packagePath);
        if (!resolved.includes(`${path.sep}.pnpm${path.sep}`)) {
          failures.push(`${item.name}: installed path is outside the pnpm virtual store.`);
        }
        const sourceMarker = `file+.openapi-to-local+${sourceHead.slice(0, 20)}`.toLowerCase();
        if (!resolved.toLowerCase().includes(sourceMarker)) {
          failures.push(`${item.name}: installed path does not identify this source SHA's local tarball.`);
        }
      } catch (error) {
        failures.push(`${item.name}: is not installed under the openapi-to aggregate: ${error.message}`);
      }
    }
  }
  if (failures.length > 0) throw new Error(failures.join("\n"));
  return packed.length;
}
